name: Request Keycloak Client
description: this issue create Keycloak clients automatically.
title: "[Client]: "
# labels: ["bug", "triage"]
# assignees:
#   - octocat
body:
  - type: input
    id: client-name
    attributes:
      label: Client Name
      description: Provide your application client name.
      placeholder: ex. react-test-app
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Environement for client?
      options:
        - dev
        - utility
    validations:
      required: true