name: Request Keycloak Client
description: this issue create Keycloak clients automatically.
title: "[Client]: "
# labels: ["bug", "triage"]
# assignees:
#   - octocat
body:
  - type: input
    id: client-name
    attributes:
      label: Client Name
      description: Provide your application client name.
      placeholder: ex. react-test-app
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      description: Please indecate the environment for the client
      placeholder: ex. dev or utility
    validations:
      required: true