name: "Issues"
on:
  issues:
    types: [opened, edited]
jobs:
  manage-keycloak-client:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: Parse issue template
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/client.yml
     
      - name: Create issue details json
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue-details.json

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Set outputs
        id: output-vars
        run: |
          echo "::set-output name=client_name::$( jq -r '.client_name' issue-details.json )"
          echo "::set-output name=client_env::$( jq -r '.environment' issue-details.json )"
      
      #TODO: remove
      - name: Echo stuff
        run: |
          echo ${{ steps.output-vars.outputs.client_name }}
          echo ${{ steps.output-vars.outputs.client_env }}

       # - name: Check out devops repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: department-of-veterans-affairs/devops
      #     token: ${{ secrets.GIT_TOKEN }}

      - name: "Run script"
        if: steps.output-vars.outputs.client_env == 'dev'
        id: ruby-script
        run: ruby parser.rb issue-details.json
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Format Terraform
        working-directory: ./temp
        run: |
          terraform fmt
          terraform fmt -check

      - name: Git configs
        if: steps.output-vars.outputs.client_env == 'dev'
        run: |
          git config --global user.email "ritesh.patel@adhocteam.us"
          git config --global user.name "Ritesh Patel"

      - name: Make changes
        if: steps.output-vars.outputs.client_env == 'dev'
        run: |
          cat temp/client.tf >> terraform/applications/keycloak/modules/login-gov/openid_clients.tf
          cat temp/variable.tf >> terraform/applications/keycloak/modules/login-gov/variables.tf
          cat temp/variable.tf >> terraform/applications/keycloak/variables.tf
          cat temp/enable.tf >> terraform/applications/keycloak/env/dev.tfvars

          sed -i -e '$ d' terraform/applications/keycloak/login-gov.tf
          echo temp/module.tf >> terraform/applications/keycloak/login-gov.tf
          echo "}" >> terraform/applications/keycloak/login-gov.tf


      - name: Create Pull Request
        if: steps.output-vars.outputs.client_env == 'dev'
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: terraform/applications/keycloak/*
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Add new client"
          branch: add-client
          base: main
          title: "[Add Keycloak Client] adding some text"
          body: |
            An automated ADD keycloak client Request
          labels: |
            amt