name: "Issues"
on:
  issues:
    types: [opened, edited]
# - run: echo ${{ github.event.issue.body }}
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/client.yml
     
      - name: "Echo Steps"
        run: |
          echo '${{ steps.issue-parser.outputs.jsonString }}' > issue-details.json
          echo '${{ steps.issue-parser.outputs.jsonString }}'
   
      - name: extract json vals
        run: |
          token=$( jq '.authorizationToken' at.json )
          echo "CLIENT_NAME=$token" >> "$GITHUB_ENV"
          echo "$CLIENT_NAME"
          
      - name: "Run ruby"
        id: ruby-script
        run: |
          ruby parser.rb '${{ steps.issue-parser.outputs.jsonString }}'

      # - name: Check out devops repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: department-of-veterans-affairs/devops
      #     token: ${{ secrets.GIT_TOKEN }}
      - name: Git checks
        run: |
          git config --global user.email "ritesh.patel@adhocteam.us"
          git config --global user.name "Ritesh Patel"
          git branch -a

      - name: Make changes
        run: |
          echo >> terraform/applications/keycloak/modules/login-gov/openid_clients.tf
          cat client.tf >> terraform/applications/keycloak/modules/login-gov/openid_clients.tf
          echo $(cat terraform/applications/keycloak/modules/login-gov/openid_clients.tf)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: terraform/applications/keycloak/*
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Add new client"
          branch: add-client
          base: main
          title: "[Add Keycloak Client] adding some text"
          body: |
            An automated ADD keycloak client Request
          labels: |
            amt