name: "Issues"
on:
  issues:
    types: [opened, edited]
# - run: echo ${{ github.event.issue.body }}
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo '${{ github.event.issue.body }}'
            echo "::endgroup::"
        continue-on-error: true
      
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/client.yml

      - run: echo '${{ step.issue-parser.outputs.jsonString s}}' > bug-details.json   

      - name: "Run ruby"
        run: ruby parser.rb '${{ step.issue-parser.outputs.jsonString s}}'