name: "Issues"
on:
  issues:
    types: [opened, edited]
# - run: echo ${{ github.event.issue.body }}
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo '${{ github.event.issue.body }}'
            echo "::endgroup::"
        continue-on-error: true

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          ref: main

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/client.yml

      - name: "Echo Steps"
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > client-details.json

      - name: "Run ruby"
        id: ruby-script
        run: |
          output=$(ruby parser.rb '${{ steps.issue-parser.outputs.jsonString }}') 
          echo "::set-output name=changelog::$output"

      # - name: Check out devops repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: department-of-veterans-affairs/devops
      #     token: ${{ secrets.GIT_TOKEN }}

      - name: Echo
        run: |
          git config --global user.email "ritesh.patel@adhocteam.us"
          git config --global user.name "Ritesh Patel"
          git checkout -b add-client

      - name: Make changes
        run: |
          echo $(cat client.tf) >> terraform/applications/keycloak/modules/login-gov/openid_clients.tf
          echo $(cat terraform/applications/keycloak/modules/login-gov/openid_clients.tf)
          git add .
          git commit -m "Add new client"
          git push -u origin add-client
      
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with: 
      #     author_name: Ritesh Patel
      #     author_email: ritesh.patel@adhocteam.us
      #     message: 'Add new client'
      #     new_branch: add-client
      #     push: origin add-client --set-upstream --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "[Add Keycloak Client] Adding new client"
          branch: add-client
          base: main
          title: "[Add Keycloak Client] adding some textß"
          body: |
            An automated ADD keycloak client Request
          labels: |
            amt