name: "Issues"
on:
  issues:
    types: [opened, edited]
# - run: echo ${{ github.event.issue.body }}
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo '${{ github.event.issue.body }}'
            echo "::endgroup::"
        continue-on-error: true

      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/client.yml

      - name: "Echo Steps"
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > client-details.json

      - name: "Run ruby"
        id: ruby-script
        run: ruby parser.rb '${{ steps.issue-parser.outputs.jsonString }}'
      
      - name: Check out devops repo
        uses: actions/checkout@v3
        with:
          repository: department-of-veterans-affairs/devops
          token: ${{ secrets.GIT_TOKEN }}

      - name: Echo
        run: |
          ls
          echo '${{ steps.ruby-script.outputs }}'
