name: "Issues"
on:
  issues:
    types: [opened, edited]
jobs:
  manage-user-groups:
    if: contains( github.event.issue.labels.*.name, 'keycloak-groups') 
    runs-on: ubuntu-latest
    steps:  
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Parse issue template
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/user-groups.yml

      - name: Create issue details json and vars
        run: |
          echo '${{ steps.issue-parser.outputs.jsonString }}' > issue-details.json
          echo "USER_GROUP=$( jq -r '.group_name' issue-details.json )" >> $GITHUB_ENV
          echo "USER_EMAIL=$( jq -r '.user_email' issue-details.json )" >> $GITHUB_ENV
          echo "USER_TEAM=$( jq -r '.team_name' issue-details.json )" >> $GITHUB_ENV
          echo "USER_ENV=$( jq -r '.environment' issue-details.json )" >> $GITHUB_ENV
      - name: Test
        run: echo $USER_GROUP