name: ci
on:
  pull_request:
    paths:
      - 'terraform/applications/keycloak/**'
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            keycloak-dev:
              - 'erraform/applications/keycloak/env/dev.tfvars'
            keycloak-utility:
              - 'erraform/applications/keycloak/env/utility.tfvars'

      - name: Echo Test
        run: |
            echo "PR test"
            echo ${ steps.changes.outputs.vagov-dev }
            echo ${ steps.changes.outputs.vagov-dev }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform fmt
        id: fmt
        working-directory: terraform/applications/keycloak
        continue-on-error: true
        run: terraform fmt -check

      - name: terraform init
        id: init
        working-directory: terraform/applications/keycloak
        continue-on-error: true
        run: terraform init