name: Keycloak Terraform
on:
  pull_request:
    paths:
      - 'terraform/applications/keycloak/**'
jobs:
  terraform-automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: echo
        run: echo “${{ toJson(github.event.pull_request.labels.*.name) }}”
        
      - name: set dev env variable        
        if: contains(github.event.pull_request.labels.*.name, 'dev')      
        run: |
           echo "KC_ENV=dev" >> "$GITHUB_ENV"
      
      - name: set staging env variable        
        if: contains(github.event.pull_request.labels.*.name, 'staging')      
        run: |
           echo "KC_ENV=staging" >> "$GITHUB_ENV"

      # - name: Set ENV
      #   run: |
      #     if [[ ${{ github.event.pull_request.labels.*.name }} == *"dev"* ]]; then
      #       echo "ENV=dev" >> "$GITHUB_ENV"
      #     elif [[ ${{ github.event.pull_request.labels.*.name }} == *"staging"* ]]; then
      #       echo "ENV=staging" >> "$GITHUB_ENV"
      #     else [[ ${{ github.event.pull_request.labels.*.name }} == *"utility"* ]]; then
      #       echo "ENV=utility" >> "$GITHUB_ENV"
      #     fi
      ## detect changes in dev or utility file, may be change to something else in future for env.
      # - uses: dorny/paths-filter@v2
      #   name: identify env
      #   id: changes
      #   with:
      #     filters: |
      #       keycloak-dev:
      #         - 'terraform/applications/keycloak/env/dev.tfvars'
      #       keycloak-utility:
      #         - 'terraform/applications/keycloak/env/utility.tfvars'

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: "us-gov-west-1"

      # - name: Obtain GitHub Token
      #   uses: marvinpinto/action-inject-ssm-secrets@latest
      #   with:
      #     ssm_parameter: /dsva-vagov/keycloak/rp_github_token #/devops/VA_VSP_BOT_GITHUB_TOKEN
      #     env_variable_name: VA_VSP_BOT_GITHUB_TOKEN

      - name: echo stuff
        run: |
            echo ${{ env.KC_ENV}} 

      - name: terraform fmt
        id: fmt-dev
        if: ${{ contains(github.event.pull_request.labels.*.names, 'dev') }}
        working-directory: terraform/applications/keycloak
        continue-on-error: true
        run: make ENV=dev fmt-check

      - name: terraform init
        id: init-dev
        if: steps.changes.outputs.keycloak-dev == 'true'
        working-directory: terraform/applications/keycloak
        continue-on-error: true
        run: make ENV=dev init

      - name: terraform plan
        id: plan-dev
        if: steps.changes.outputs.keycloak-dev == 'true'
        working-directory: terraform/applications/keycloak
        run: make ENV=dev plan-no-refresh
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request' && steps.changes.outputs.keycloak-dev == 'true'
        env:
          FMT: "${{ steps.fmt-dev.outputs.stdout }}"
          PLAN: "${{ steps.plan-dev.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt-dev.outcome }}\`

            <details><summary>Files in need of format</summary>
            
            \`\`\`\n
            ${process.env.FMT}
            \`\`\`
            
            </details>

            #### Terraform Initialization ⚙️\`${{ steps.init-dev.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan-dev.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>

            #### *Environment: dev*`;
      
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })